apiVersion: apps/v1
kind: Deployment
metadata:
  name: f21ao-cw2
  labels:
    app.kubernetes.io/name: f21ao-cw2-deploy
    app.kubernetes.io/component: f21ao-cw2-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: f21ao-cw2-deploy
      app.kubernetes.io/component: f21ao-cw2-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: f21ao-cw2-deploy
        app.kubernetes.io/component: f21ao-cw2-deploy
    spec:
      containers:
        - name: f21ao-cw2
          image: pp2002/f21ao
          imagePullPolicy: Never # use local image
          ports:
            - containerPort: 8088

---
apiVersion: apps/v1
kind: Service
metadata:
  name: f21ao-cw2
  labels:
    app: f21ao-cw2-deploy
spec:
  type: NodePort
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
    nodePort: 32121
  selector:
    app: f21ao-cw2-deploy
