apiVersion: apps/v1
kind: Deployment
metadata:
  name: f21ao-cw2
  labels:
    app.kubernetes.io/name: f21ao-cw2-deploy
    app.kubernetes.io/component: f21ao-cw2-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: f21ao-cw2-deploy
      app.kubernetes.io/component: f21ao-cw2-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: f21ao-cw2-deploy
        app.kubernetes.io/component: f21ao-cw2-deploy
    spec:
      containers:
        - name: f21ao-cw2
          image: pp2002/f21ao:latest
          imagePullPolicy: Never # use local image
          ports:
            - containerPort: 8088
