apiVersion: v1
kind: Service
metadata:
  name: f21ao
  labels:
    app.kubernetes.io/name: f21ao-service
    app.kubernetes.io/component: f21aoservice
spec:
  type: NodePort
  #hostNetwork: true
  externalIPS: localhost
  ports:
    - port: 8095
      protocol: TCP
      targetPort: 8095
      nodePort: 32111
  selector:
    app.kubernetes.io/name: f21ao-service
    app.kubernetes.io/component: f21aoservice
