apiVersion: v1
kind: Service
metadata:
  name: f21ao
  labels:
    app.kubernetes.io/name: f21ao-service
    app.kubernetes.io/component: f21aoservice
spec:
  type: NodePort
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
      nodePort: 32121
  selector:
    app.kubernetes.io/name: f21ao-service
    app.kubernetes.io/component: f21aoservice
